// <auto-generated />
using System;
using HomeMaintenanceAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeMaintenanceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713234352_removingAmountFromPaymentRequest")]
    partial class removingAmountFromPaymentRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RelatedOfferId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedSubscriptionPaymentRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedOfferId");

                    b.HasIndex("RelatedOrderId");

                    b.HasIndex("RelatedSubscriptionPaymentRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletionTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<int?>("SelectedProviderProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SelectedProviderProfileId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Order_Latitude", "[Latitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_Order_Longitude", "[Longitude] BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.ProviderOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InspectionPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProviderLatitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("ProviderLongitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<int>("ProviderProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProviderProfileId");

                    b.HasIndex("OrderId", "ProviderProfileId")
                        .IsUnique();

                    b.ToTable("ProviderOffers", t =>
                        {
                            t.HasCheckConstraint("CK_ProviderOffer_InspectionPrice", "[InspectionPrice] >= 0");

                            t.HasCheckConstraint("CK_ProviderOffer_Latitude", "[ProviderLatitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_ProviderOffer_Longitude", "[ProviderLongitude] BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.ProviderProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProviderProfiles");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.ProviderSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProviderProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionPaymentRequestId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProviderProfileId");

                    b.HasIndex("SubscriptionPaymentRequestId")
                        .IsUnique();

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("ProviderSubscriptions");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProviderProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ProviderProfileId");

                    b.ToTable("Ratings", t =>
                        {
                            t.HasCheckConstraint("CK_Rating_Value", "[Value] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.SubscriptionPaymentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("ProofImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProviderProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderProfileId");

                    b.HasIndex("ReviewedByAdminId");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("SubscriptionPaymentRequests");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", t =>
                        {
                            t.HasCheckConstraint("CK_SubscriptionPlan_Duration", "[DurationInDays] > 0");

                            t.HasCheckConstraint("CK_SubscriptionPlan_Price", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EmailVerificationCodeExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailVerificationCodeHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetCodeExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetCodeHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.Notification", b =>
                {
                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.ProviderOffer", "RelatedOffer")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedOfferId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.Order", "RelatedOrder")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedOrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.SubscriptionPaymentRequest", "RelatedSubscriptionPaymentRequest")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedSubscriptionPaymentRequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RelatedOffer");

                    b.Navigation("RelatedOrder");

                    b.Navigation("RelatedSubscriptionPaymentRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.Order", b =>
                {
                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.User", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.ProviderProfile", "SelectedProviderProfile")
                        .WithMany("SelectedOrders")
                        .HasForeignKey("SelectedProviderProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.Specialization", "Specialization")
                        .WithMany("Orders")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SelectedProviderProfile");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.ProviderOffer", b =>
                {
                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.Order", "Order")
                        .WithMany("Offers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.ProviderProfile", "ProviderProfile")
                        .WithMany("Offers")
                        .HasForeignKey("ProviderProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProviderProfile");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.ProviderProfile", b =>
                {
                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.Specialization", "Specialization")
                        .WithMany("ProviderProfiles")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.User", "User")
                        .WithOne("ProviderProfile")
                        .HasForeignKey("HomeMaintenanceAPI.Domain.Entities.ProviderProfile", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.ProviderSubscription", b =>
                {
                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.ProviderProfile", "ProviderProfile")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ProviderProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.SubscriptionPaymentRequest", "SubscriptionPaymentRequest")
                        .WithOne("ProviderSubscription")
                        .HasForeignKey("HomeMaintenanceAPI.Domain.Entities.ProviderSubscription", "SubscriptionPaymentRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("ProviderSubscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProviderProfile");

                    b.Navigation("SubscriptionPaymentRequest");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.Rating", b =>
                {
                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.User", "Customer")
                        .WithMany("Ratings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.Order", "Order")
                        .WithOne("Rating")
                        .HasForeignKey("HomeMaintenanceAPI.Domain.Entities.Rating", "OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.ProviderProfile", "ProviderProfile")
                        .WithMany("Ratings")
                        .HasForeignKey("ProviderProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("ProviderProfile");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.SubscriptionPaymentRequest", b =>
                {
                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.ProviderProfile", "ProviderProfile")
                        .WithMany("SubscriptionPaymentRequests")
                        .HasForeignKey("ProviderProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.User", "ReviewedByAdmin")
                        .WithMany("ReviewedSubscriptionPaymentRequests")
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeMaintenanceAPI.Domain.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("SubscriptionPaymentRequests")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProviderProfile");

                    b.Navigation("ReviewedByAdmin");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.Order", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Offers");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.ProviderOffer", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.ProviderProfile", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Ratings");

                    b.Navigation("SelectedOrders");

                    b.Navigation("SubscriptionPaymentRequests");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProviderProfiles");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.SubscriptionPaymentRequest", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("ProviderSubscription");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("ProviderSubscriptions");

                    b.Navigation("SubscriptionPaymentRequests");
                });

            modelBuilder.Entity("HomeMaintenanceAPI.Domain.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("ProviderProfile");

                    b.Navigation("Ratings");

                    b.Navigation("ReviewedSubscriptionPaymentRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
